apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Dev: uses images from quay.io/redhat-user-workloads
images:
  - name: quay.io/kuadrant/coredns-kuadrant
    newName: image-rbac-proxy.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/redhat-user-workloads/api-management-tenant/rhcl-1-3-coredns
    digest: sha256:c2e49ae0c68c322450324c38c5386163bf86b490d2361abeb09b6c38167a7618
