# # Based on ./gatekeeper-operator/bundle.Dockerfile
FROM registry.redhat.io/ubi9/ubi@sha256:d4feb579a84ead49894ec71fe54f14300992e202f3491d9bb22b62cc57affd49 AS builder-runner

RUN dnf install -y skopeo jq python3 python3-pip && \
    pip3 install ruamel.yaml

# Use a new stage to enable caching of the package installations for local development
FROM builder-runner AS builder

# Automating bundle reference updates via Konflux requires us to maintain our own CSV file
COPY ./bundle-hack/ .
COPY dns-operator/bundle/manifests /manifests/
RUN rm /manifests/dns-operator.clusterserviceversion.yaml
COPY ./downstream-conversion/bundle/manifests/dns-operator.clusterserviceversion.yaml /manifests
COPY ./downstream-conversion/bundle/metadata /metadata/
RUN chmod +x update_bundle.sh && development=true ./update_bundle.sh

FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=rhcl-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable

LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

# Core bundle labels.
LABEL version="1.1.1" \
    summary="Red Hat Connectivity Link enables you to secure, protect, and connect your APIs and applications in multicluster, multicloud, and hybrid cloud environments" \
    name="dns-operator-bundle" \
    description="Red Hat Connectivity Link enables you to secure, protect, and connect your APIs and applications in multicluster, multicloud, and hybrid cloud environments" \
    distribution-scope="public" \
    release="1.1.1" \
    url="" \
    com.redhat.component="Red Hat DNS Operator Bundle" \
    io.k8s.display-name="Red Hat Connectivity Link Operator metadata" \
    io.k8s.description="Red Hat DNS Operator Bundle" \
    io.openshift.expose-services="" \
    io.openshift.tags="api" \
    vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY --from=builder /manifests /manifests/
COPY --from=builder /metadata /metadata/
COPY dns-operator/bundle/tests/scorecard /tests/scorecard/
