FROM scratch

LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1
LABEL operators.operatorframework.io.bundle.manifests.v1=manifests/
LABEL operators.operatorframework.io.bundle.metadata.v1=metadata/
LABEL operators.operatorframework.io.bundle.package.v1=rhcl-operator
LABEL operators.operatorframework.io.bundle.channels.v1=stable
LABEL operators.operatorframework.io.bundle.channel.default.v1=stable

LABEL operators.operatorframework.io.metrics.builder=operator-sdk-v1.34.1
LABEL operators.operatorframework.io.metrics.mediatype.v1=metrics+v1
LABEL operators.operatorframework.io.metrics.project_layout=go.kubebuilder.io/v3

# Labels for testing.
LABEL operators.operatorframework.io.test.mediatype.v1=scorecard+v1
LABEL operators.operatorframework.io.test.config.v1=tests/scorecard/

# Core bundle labels.
LABEL version="1.4.0" \
      summary="Red Hat Connectivity Link enables you to secure, protect, and connect your APIs and applications in multicluster, multicloud, and hybrid cloud environments" \
      name="rhcl-1/dns-operator-bundle" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      description="Red Hat Connectivity Link enables you to secure, protect, and connect your APIs and applications in multicluster, multicloud, and hybrid cloud environments" \
      distribution-scope="public" \
      release="1.4.0" \
      url="" \
      com.redhat.component="Red Hat DNS Operator Bundle" \
      io.k8s.display-name="Red Hat Connectivity Link Operator metadata" \
      io.k8s.description="Red Hat DNS Operator Bundle" \
      io.openshift.expose-services="" \
      io.openshift.tags="api" \
      vendor="Red Hat, Inc."

# Copy files to locations specified by labels.
COPY bundle-dev/manifests /manifests/
COPY bundle-dev/metadata /metadata/
COPY dns-operator/bundle/tests/scorecard /tests/scorecard/
COPY coredns/manifests/dev/ /coredns/
