FROM registry.redhat.io/ubi9/go-toolset@sha256:5f5c97d7e6d917b8328321bcf2c9d5700de65b72d434ecdbbba6f35aaebaad40 AS builder

# TODO: cleanup if not needed
#ENV LDFLAGS="-X ${VERSION_PKG}.gitVersion=v3.15.1-7 \
#             -X ${VERSION_PKG}.gitCommit=59587323ce32580b4dffba0a09b1ca22109925db \
#             -X ${VERSION_PKG}.gitTreeState=clean \
#             -X ${VERSION_PKG}.buildDate="

ENV LDFLAGS="-X ${VERSION_PKG}.buildDate="
ENV BINARY_NAME="manager"

WORKDIR /workspace

# Copy the Go Modules manifests
COPY dns-operator/go.mod go.mod
COPY dns-operator/go.sum go.sum

# cache deps before building and copying source so that we don't need to re-download as much
# and so that source changes don't invalidate our downloaded layer
RUN go mod download

# Copy the go source
COPY ./dns-operator/cmd/main.go cmd/main.go
COPY ./dns-operator/api/ api/
COPY ./dns-operator/internal/ internal/
COPY ./dns-operator/types/ types/

COPY dns-operator/LICENSE /licenses/LICENSE

# Build
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} go build -ldflags "-X main.version=${VERSION} -X main.gitSHA=${GIT_SHA} -X main.dirty=${DIRTY}" -a -o ${BINARY_NAME} cmd/main.go

FROM registry.redhat.io/ubi9/ubi-minimal@sha256:2e8edce823a48e51858f1fad3ff4cbf6875ce8a3f86b9eecf298bc2050c8652a

LABEL version="0.16.2" \
      summary="Red Hat DNS Operator Container Image" \
      description="Red Hat DNS Operator Container Image" \
      name="rhcl-1/dns-rhel9-operator" \
      cpe="cpe:/a:redhat:connectivity_link:1::el9" \
      com.redhat.component="Red Hat DNS Operator" \
      io.k8s.display-name="Red Hat DNS Operator" \
      io.k8s.description="Red Hat DNS Operator Container Image" \
      io.openshift.expose-services="" \
      io.openshift.tags="api" \
      vendor="Red Hat, Inc."

ENV OPERATOR_BINARY_NAME="manager" \
    USER_UID=1001 \
    USER_NAME=connectivity-link-operator

USER root

# install operator binary
COPY --from=builder /workspace/${OPERATOR_BINARY_NAME} /
RUN chown ${USER_UID} /${OPERATOR_BINARY_NAME}

COPY --from=builder licenses/LICENSE /licenses/LICENSE

# # TODO: Install licenses
# ENV LICENSES_DIR="/licenses/apicast-operator/"
# RUN mkdir -p ${LICENSES_DIR}
# COPY rh-connectivity-link-operator/dns-operator/licenses.xml ${LICENSES_DIR}
# RUN chown ${USER_UID} ${LICENSES_DIR}/licenses.xml

ENTRYPOINT ["/manager"]

USER ${USER_UID}