apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Stage: uses images from registry.stage.redhat.io
images:
  - name: quay.io/kuadrant/coredns-kuadrant
    newName: registry.stage.redhat.io/rhcl-1/coredns-rhel9
    digest: sha256:5f48f593db165fb6c90116251a5052de719f644c2ba432db0e94eb515c08c790
